- name: Install PostgreSQL
  hosts: best_server
  remote_user: root
  become: true
  roles:
    - buluma.timezone
    - kdv.langpacks
    - geerlingguy.postgresql
    - kdv.check_postgresql
  vars:
    timezone: Europe/Moscow
    postgresql_users:
      - name: student
        password: # указать пароль
      - name: remoteuser
        password: # указать пароль
    postgresql_databases:
      - name: studentdb
      - name: remotedb
    postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      - option: unix_socket_directories
        value: '{{ postgresql_unix_socket_directories | join(",") }}'
      - option: log_directory
        value: '/var/log'
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: remotedb, user: remoteuser, address: 'all', auth_method: md5 }
      - { type: host, database: studentdb, user: student, address: "{{bad_server}}/32", auth_method: md5 }
