- name: Install PostgreSQL
  hosts: best_server
  remote_user: root
  become: true
  roles:
    - buluma.timezone
    - kdv.langpacks
    - geerlingguy.firewall
    - geerlingguy.postgresql
    - kdv.check_postgresql
  vars:
    timezone: Europe/Moscow
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_disable_firewalld: true
    firewall_disable_ufw: true
    firewall_enable_ipv6: false
    firewall_allowed_tcp_ports:
      - "22"
      - "53"
      - "5432"
    firewall_allowed_udp_ports:
      - "53"
    postgres_users_no_log: false
    postgresql_users:
      - name: student
        password: # указать пароль
      - name: remoteuser
        password: # указать пароль
    postgresql_databases:
      - name: studentdb
      - name: remotedb
    postgresql_privs:
      - db: studentdb
        privs: ALL
        type: database
        roles: student
      - db: remotedb
        privs: ALL
        type: database
        roles: remoteuser
    postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      - option: unix_socket_directories
        value: '{{ postgresql_unix_socket_directories | join(",") }}'
      - option: log_directory
        value: '/var/log'
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: host, database: remotedb, user: remoteuser, address: all, auth_method: md5 }
      - { type: host, database: studentdb, user: student, address: "{{bad_server}}/32", auth_method: md5 }
